spring:
  datasource:
    url: jdbc:mysql://www.followyourdreams.cn:3306/common-96110?autoReconnect=true&allowMultiQueries=true&useUnicosde=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useSSL=false
    username: root
    password: happy521
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
      minimum-idle: 5 # 池中维护的最小空闲连接数，默认为 10 个。
      idle-timeout: 30000

  data:
    redis:
      host: localhost
      port: 6379
      database: 1


